import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import {DM_Sans,Bricolage_Grotesque } from "next/font/google";
import "./globals.css";

const dmSans = DM_Sans({ weight: ["300", "500", "600", "700"] });
const bricolage = Bricolage_Grotesque({weight:["700"]})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${dmSans.className}  antialiased`}
      >
       
        {children}
      </body>
    </html>
  );
}
